### ISSUE TITLE
How do I customize the database user credentials?

### ISSUE THREAD

**Issue by bkuhl** [davidsoergel/s3napback#6]
I'm currently running into an issue where I get the below error during mysql backups:

`mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: NO)" when trying to connect`

Is there a way for me to customize the credentials for the database connection?

**Comment by davidsoergel** [comment]
The user you're running the script as must be able to mysqldump the requested databases without entering a password. This can be accomplished through the use of a .my.cnf file in the user's home directory, containing e.g.

```
[mysqldump]
user=mysqluser
password=secret
```
